<?php
return [
    'version' => 'v5.10.7',
    'build' => '20260810',
    'version_code' => 51007,
    'commit' => 'autoupdate-progress-ui',
    'updated_at' => '2026-08-10',
    'changelog' => [
        'v5.10.7' => [
            'date' => '2026-08-10',
            'title' => '【后台自动更新进度条可视化】一键操作+进度跟踪+彩色日志',
            'changes' => [
                '后台「系统管理」分组新增「🔄 自动更新/维护」菜单项（page-autoupdate），进度条徽章标识',
                '进度条 UI：渐变紫色进度条 + 条纹动画，支持 0-100% 平滑过渡，显示百分比和当前步骤',
                '步骤详情卡片：按任务权重渲染每个子步骤，待执行(灰)/执行中(蓝动)/成功(绿✅)/失败(红❌) 四态彩色显示',
                '彩色日志区域：info/warn/error/ok(success) 四色分级显示，支持自动滚动开关 + 手动滚动',
                '操作面板：action 下拉(all/check/migrate/official_refresh/ai_learn/site_check/status/reset_key)、max 数量、force 强制',
                '按钮：开始执行 / 刷新进度 / 停止轮询 / 重置密钥 / 手动清理旧进度 五合一操作面板',
                'gx.php 进度跟踪升级：新增 GxProgressTracker 类，通过 gx/.gx_progress.json 记录步骤权重/百分比/日志/耗时',
                'gx.php 异步执行：gx_launch_async() 支持 exec() CLI 后台启动，禁用时回退到同步执行不阻塞 HTTP',
                'gx_execute.php 安全启动接口：HMAC-SHA256 签名 + 时间戳 ±24h，action 白名单校验，支持 exec()/fsockopen 双通道启动',
                'gx_progress.php 进度查询接口：返回当前任务进度 + 历史执行记录，支持后台轮询（1.2s/次，自动停止）',
                '【重点修复】签名生成改为服务端 gx_token.php：彻底解决 Web Crypto API 需 HTTPS 安全上下文（HTTP/IP 访问不可用）、以及手写 JS HMAC 与 PHP 不一致的问题',
                '安全增强：mxadmin.php 不再将 gx_secret 明文暴露到前端 JS，仅输出 __GX_SECRET_READY__ 标志，签名统一由 gx_token.php 服务端生成',
                'gx_execute.php 修复：HTTP_HOST 含端口时不再重复拼接 SERVER_PORT，max=null 字符串/JSON null/空/PHP null 四态全部统一识别为 null',
                '浏览器端测试验证：action=status 任务 0s 完成，进度条→100%，步骤详情✅，彩色日志3条正确追加，轮询自动停止',
                '后端集成测试通过：gx_token.php 生成签名 → gx_execute.php 校验通过 → 任务启动success:true → gx_progress.php 读取 percent=100%',
            ],
        ],
        'v5.10.6' => [
            'date' => '2026-08-10',
            'title' => '【gx.php 线上错误修复 v2】check/migrate/official_refresh 三大任务修复',
            'changes' => [
                '修复 check 任务 exec() 被禁用报错：禁用时改为 tokenizer 软校验（token_get_all），避免 Call to undefined function exec()',
                '语法校验兼容：function_exists(exec) → php -l / token_get_all 双通道，线上 disable_functions 环境零报错',
                '修复 migrate 任务：DataMigration 实际方法名是 migrateAll，新增按优先级尝试 migrateAll → runAll → migrate → run；无方法时走手动 pipeline(migrateDomainRules+migrateResourceSites+migrateOfficialPlatforms 等)',
                '修复 official_refresh default_site=量子 纠正为抖剧TV：新增 ensureDoujuDefault() 自动写入/更新抖剧资源站/官替平台，default_site/search_sites 首位强制抖剧TV',
                '官替阈值纠正：若 match_threshold 过高(>75) 自动降到推荐 65，enabled=true 默认开启',
                '官替抽检 searchAllSites 不存在时 3 级回退：DbResourceSiteManager::searchAllSites → OfficialReplaceManager::searchInSites → 直接遍历前3个资源站searchVideos 逐个试',
                '官替抽检新增 spot_sample：返回前3个命中视频样例(name/site/remarks)，便于排查空结果',
                '官替平台 count 8个：含抖剧TV平台（360kan.com/抖剧TV 根源来源 priority=1）',
            ],
        ],
        'v5.10.5' => [
            'date' => '2026-08-09',
            'title' => '【新增 gx.php 全局定时/自动更新调度中心】',
            'changes' => [
                '新增 gx.php v1.0：全局调度中心（CLI+Web 双模式，一键全部 or 单项）',
                'CLI 子命令：all / status / check / migrate / ai_learn / ai_cleanup / official_refresh / site_check / rule_check / reset_key',
                'Web 模式：自动生成随机32位密钥 gx/.gx_secret.php，访问 ?key=密钥&action=动作',
                '互斥锁机制 (flock+pid)：防止 crontab 重叠运行 DB 死锁',
                '分模块异常隔离：一个模块挂不影响其它模块',
                '结构化日志 gx/gx_run.log + 最后一次执行摘要 gx/.gx_last_run.php',
                'task_check 健康检查：本地版本、核心文件存在性、语法 spot-check、目录可写、PHP版本',
                'task_migrate：DataMigration 自动升级 DB schema',
                'task_ai_learn：调用 AiAutoLearner::run()（force 忽略间隔，立即学）',
                'task_ai_cleanup：调用 AiAutoLearner::cleanupStaleRules() 清理失效规则域名',
                'task_official_refresh：官替配置重载 + 缓存清理 + 搜索抽检（随机热门词）',
                'task_site_check：资源站随机API健康巡检（返回OK/FAIL/cost_ms/videos数）',
                'task_rule_check：随机抽样 gz/rules_*.php 域名做 HTTPS HEAD 健康检查',
                '兼容修复：DbResourceSiteManager curl_close 在 PHP 8.0+ 已废弃改为 null',
            ],
        ],
        'v5.10.4' => [
            'date' => '2026-08-09',
            'title' => '【官替识别大优化 v2】全链路修复识别不准、漏配、搜索无结果问题',
            'changes' => [
                'resolve() 短链重定向解析：b23.tv/微信跳转/快手短链自动走 resolveRedirectChain 最多5跳重定向',
                'resolve() URL 规范化：去锚点、无前缀补 https、//scheme 自动补全',
                '新增 detectPlatformFuzzy() 模糊平台识别：移动站子域名(m.v.qq/m.iqiyi/m.mgtv/m.bilibili/360kan/film.qq) 全部命中',
                '360kan.com 域名自动识别为抖剧TV 官替平台（根源来源）',
                'extractVideoId() 大扩展：芒果 /b/xxxx、爱奇艺 aid/albumId、youku show_id、搜狐 vod/shtml id、PPTV programId、抖剧TV vod/detail/id',
                '移动站URL 2次尝试 extract：extract 失败时自动 guessMobileUrl 换成 m.*.com URL 重试',
                'httpGet() 升级：自动伪造 Referer/Origin（按域名推导）、br brotli 解压、sec-ch-ua 伪造、403/500/429 重试、3xx带body放行',
                'httpGetMobile() 2次重试 + 最终回退增强版httpGet',
                'cleanTitle() 强解码：&#中文实体/html_entity_decode/\\uXXXX(\\u5e86这类) Unicode 转义 精准解码',
                'cleanTitle() 强清洗：平台名后缀25+种/画质/分辨率/预告/花絮/MV/纪录片/直播/演唱会/广告 等过滤',
                'DbResourceSiteManager searchVideos() 5策略搜索：ac=list→videolist→detail→list+t=1,2,3,4→list+h=24（苹果CMS10最通用 ac=list 排第一）',
                '关键词变体搜索（含空格/下划线/去空格/去集季）+ JSONP callback 包装自动去除',
                'findBestMatch() 阈值动态三级：主阈值60 / fallbackThreshold(60-18=42) / hardFloorThreshold(35) 避免漏配',
                'findBestMatch() 新增年份+演员交叉验证（命中演员+6/人，最多18分；年份相同+12，±1年+4，差太远-8）',
                'findBestMatch() 非正片排除正则 50+种：从"解说/预告/片花/速看/混剪/Reaction/MV/花絮/直播回放/饭制/二创/广告/纪录片"到具体"定档预告/超长花絮/生日直播/红毯盛典/发布会/番外/彩蛋"',
                '基础匹配多关键词变体取最高分（base_title/title/parsed.base_title/pure_title 逐个试）',
                '验证脚本 22/22 100% 通过：13平台识别 + 4抖剧TV搜索 + 3官替配置 + 4cleanTitle',
            ],
        ],
        'v5.10.3' => [
            'date' => '2026-08-10',
            'title' => '【官替升级】新增抖剧TV 默认官替资源站 + 官替优先度 1-2000+',
            'changes' => [
                '新增官替资源站：抖剧TV（采集接口 https://www.douju.tv/api.php/provide/vod/，根源来源 www.360kan.com）',
                '设置抖剧TV 为默认官替资源站（default_site=抖剧TV，官替 search_sites 数组第1位=抖剧TV）',
                '抖剧TV 资源站 priority=1（数字越小越优先，1-2000+ 支持任意数字）',
                '抖剧TV 官替平台 priority=1，与腾讯/爱奇艺/优酷/芒果/B站 同为最优先梯队，但在 search_sites 固定第一',
                '后台官替管理页面：新增默认官替站显示、priority 升序表格 + 彩色徽章（⭐默认官替 / 高优先 / 普通 / 低优先）',
                '官替优先度编辑器：min=1 max=2000 step=1，附"数字越小越优先，1=最高"说明',
                '后台官替 API 配置：新增 default_site 输入框 + priority 规则说明渐变色提示条',
                'DbOfficialReplaceManager::searchInSites() 改为优先使用 DbResourceSiteManager（含 priority ASC 排序 + 最新资源站）',
                'DbOfficialReplaceManager::getDefaultConfig() 默认 default_site=抖剧TV，search_sites 头位抖剧TV，match_threshold=70',
                '官替匹配平台查询：getAllPlatforms / getPlatformByDomain 全部按 priority ASC 排序（1=最先匹配）',
                '资源站列表：抖剧TV 归类 group_name=官替资源站，root_source=www.360kan.com，official_replace=1',
            ],
        ],
        'v5.10.2' => [
            'date' => '2026-08-09',
            'title' => '后台菜单完善 + 官替平台 editor 修复',
            'changes' => [
                '后台 mxadmin.php 新增 AI自动学习 / CCTV直播源 菜单分组和页面',
                '官替平台 editor 支持 priority 输入',
                '修复 header Warning、反射私有属性访问、DataMigration rules 列白名单等问题',
            ],
        ],
        'v5.10.1' => [
            'date' => '2026-08-08',
            'title' => '新增 CCTV 直播源扩展模块',
            'changes' => [
                '新增 cctv/CctvSourceManager.php：GitHub 官方源抓取解析 + 定时自动更新',
                '新增 cctv/CctvSourceVerifier.php：源可用性验证',
                '新增 cctv/CctvPlaylistGenerator.php：M3U8 生成 + 播放页面集成',
            ],
        ],
        'v5.10.0' => [
            'date' => '2026-08-05',
            'title' => '新增 AI 自动学习模块（苹果CMS10接口分析）',
            'changes' => [
                '新增 ai_learn/MacCMS10Analyzer.php：苹果CMS10 采集接口分析 + 去除非正片内容',
                '新增 ai_learn/AutoLearnEngine.php：从资源站随机抓取视频 → 广告分析 → 学习规则',
                '新增 ai_learn/TaskScheduler.php：定时任务调度，确保无广告且正片',
                '新增 ai_learn/AiEndpointRouter.php：AI 接口地址配置化自动切换',
            ],
        ],
        'v5.9.7' => [
            'date' => '2026-08-03',
            'title' => 'M3U8 广告过滤系统基础版本',
            'changes' => [
                '核心 M3U8AdSkipper + AdFilter：M3U8 广告分析与过滤',
                'DataMigration 数据库迁移 + 官替/资源站/规则 SQLite 表',
                '后台资源站管理 + 规则管理 + 数据库管理',
            ],
        ],
    ],
];