<?php return array (
  'domain' => 'corruptdebug1783360480.com',
  'duration_rules' => 'corrupted',
  'discontinuity_rules' => 123,
  'sequence_jump_rules' => NULL,
  'filename_patterns' => 'not_array',
  'insertion_patterns' => 'bad',
  'ad_type_stats' => 'bad',
  'psychological_profile' => 'bad',
  'history_stats' => 'bad',
  'marker_stats' => 'bad',
  'learn_count' => 2,
  'ad_threshold' => 'fifty',
  'confidence_score' => 'high',
);