<?php
/**
 * 代理池配置
 * 自动更新于: 2026-07-17 05:07:59
 */

return [
    'version' => '2.0',
    'enabled' => true,
    'auto_switch' => true,
    'auto_refresh' => true,
    'check_interval' => 300,
    'timeout' => 10,
    'proxies' => [
        [
            'id' => 'c7a798feed6de1cf8cb89cfb62156342',
            'name' => 'HTTP 8.130.74.114:1080',
            'type' => 'http',
            'host' => '8.130.74.114',
            'port' => 1080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:06:54',
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '94154400666f76a4d5720ef960b11f32',
            'name' => 'HTTP 45.229.17.164:999',
            'type' => 'http',
            'host' => '45.229.17.164',
            'port' => 999,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:06:54',
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => 'ecb9ed9544c88018251a19bac4708637',
            'name' => 'HTTP 182.253.181.10:8080',
            'type' => 'http',
            'host' => '182.253.181.10',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:06:54',
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '4f55c03d204ff74d05de089a0f3a5ef5',
            'name' => 'HTTP 24.133.202.138:3310',
            'type' => 'http',
            'host' => '24.133.202.138',
            'port' => 3310,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:06:54',
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '4b3c458343c33ccac7fe5f99d8e53a0f',
            'name' => 'HTTP 54.206.129.120:58291',
            'type' => 'http',
            'host' => '54.206.129.120',
            'port' => 58291,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:06:54',
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '2a0415310cfb3f9f98cf35187082a102',
            'name' => 'HTTP 147.161.177.132:10272',
            'type' => 'http',
            'host' => '147.161.177.132',
            'port' => 10272,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:07:59',
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => 'eaa082b4614eeb83c72ae7e368ec9324',
            'name' => 'HTTP 47.250.177.202:199',
            'type' => 'http',
            'host' => '47.250.177.202',
            'port' => 199,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:07:59',
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '61679470fe67c0f03883cb8ca235a585',
            'name' => 'HTTP 103.189.97.134:8082',
            'type' => 'http',
            'host' => '103.189.97.134',
            'port' => 8082,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:07:59',
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '52b33aea755cc8cb0595ced51946ee12',
            'name' => 'HTTP 18.190.253.157:9944',
            'type' => 'http',
            'host' => '18.190.253.157',
            'port' => 9944,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:07:59',
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '18ea978ffd172ab472fe481c523fc7e5',
            'name' => 'HTTP 165.225.192.37:12669',
            'type' => 'http',
            'host' => '165.225.192.37',
            'port' => 12669,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:07:59',
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => 'test_proxy_1',
            'name' => 'Test Proxy 1',
            'type' => 'http',
            'host' => '192.168.1.1',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:06:54',
            'last_success' => NULL,
            'response_time' => 100,
            'country' => '中国'
        ],
        [
            'id' => 'test_proxy_2',
            'name' => 'Test Proxy 2',
            'type' => 'http',
            'host' => '192.168.1.2',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:06:54',
            'last_success' => NULL,
            'response_time' => 100,
            'country' => '中国'
        ],
        [
            'id' => 'test_proxy_3',
            'name' => 'Test Proxy 3',
            'type' => 'http',
            'host' => '192.168.1.3',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 1,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:07:59',
            'last_success' => '2026-07-17 05:06:54',
            'response_time' => 100,
            'country' => '中国'
        ],
        [
            'id' => 'test_proxy_4',
            'name' => 'Test Proxy 4',
            'type' => 'http',
            'host' => '192.168.1.4',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:07:59',
            'last_success' => NULL,
            'response_time' => 100,
            'country' => '中国'
        ],
        [
            'id' => 'test_proxy_5',
            'name' => 'Test Proxy 5',
            'type' => 'http',
            'host' => '192.168.1.5',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 1,
            'last_check' => '2026-07-17 05:07:59',
            'last_success' => NULL,
            'response_time' => 100,
            'country' => '中国'
        ],
        [
            'id' => '1d4b4bfe92d2305278df0f0925b7e5ef',
            'name' => 'HTTP 165.225.72.38:10546',
            'type' => 'http',
            'host' => '165.225.72.38',
            'port' => 10546,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 1,
            'fail_count' => 0,
            'last_check' => '2026-07-17 05:07:59',
            'last_success' => '2026-07-17 05:07:59',
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => 'd5767799710540f1506ab421bbc477a1',
            'name' => 'HTTP 103.135.189.129:84',
            'type' => 'http',
            'host' => '103.135.189.129',
            'port' => 84,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => 'a01094c8b68665a684b47b252577c2cf',
            'name' => 'HTTP 170.245.133.49:999',
            'type' => 'http',
            'host' => '170.245.133.49',
            'port' => 999,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => 'a4bad1c0f2cd459eab691f822a7e5496',
            'name' => 'HTTP 47.121.183.107:20000',
            'type' => 'http',
            'host' => '47.121.183.107',
            'port' => 20000,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '179688b809366b939645d6f3084e9b56',
            'name' => 'HTTP 8.211.195.173:8008',
            'type' => 'http',
            'host' => '8.211.195.173',
            'port' => 8008,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => 'b1ccc44ed702bea25a54573f3c61f15a',
            'name' => 'HTTP 8.134.149.133:8008',
            'type' => 'http',
            'host' => '8.134.149.133',
            'port' => 8008,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => 'b5369d25d07ae2d0832b472b32e781b5',
            'name' => 'HTTP 200.10.31.158:999',
            'type' => 'http',
            'host' => '200.10.31.158',
            'port' => 999,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '5d6102075a36b2c8181d0bb07a475539',
            'name' => 'HTTP 203.175.103.169:8080',
            'type' => 'http',
            'host' => '203.175.103.169',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '0e141ebd2fa65df5065b248eed429eee',
            'name' => 'HTTP 103.229.185.157:8080',
            'type' => 'http',
            'host' => '103.229.185.157',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => '0dde94d5587b372d0362b053918a0603',
            'name' => 'HTTP 134.209.13.77:8080',
            'type' => 'http',
            'host' => '134.209.13.77',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 0,
            'country' => '中国'
        ],
        [
            'id' => 'test_proxy_1',
            'name' => 'Test Proxy 1',
            'type' => 'http',
            'host' => '192.168.1.1',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 100,
            'country' => '中国'
        ],
        [
            'id' => 'test_proxy_2',
            'name' => 'Test Proxy 2',
            'type' => 'http',
            'host' => '192.168.1.2',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 100,
            'country' => '中国'
        ],
        [
            'id' => 'test_proxy_3',
            'name' => 'Test Proxy 3',
            'type' => 'http',
            'host' => '192.168.1.3',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 100,
            'country' => '中国'
        ],
        [
            'id' => 'test_proxy_4',
            'name' => 'Test Proxy 4',
            'type' => 'http',
            'host' => '192.168.1.4',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 100,
            'country' => '中国'
        ],
        [
            'id' => 'test_proxy_5',
            'name' => 'Test Proxy 5',
            'type' => 'http',
            'host' => '192.168.1.5',
            'port' => 8080,
            'username' => '',
            'password' => '',
            'status' => 'active',
            'priority' => 50,
            'success_count' => 0,
            'fail_count' => 0,
            'last_check' => NULL,
            'last_success' => NULL,
            'response_time' => 100,
            'country' => '中国'
        ]
    ]
];
