<?php

class OutputGenerator {
    private $options = [];

    public function __construct($options = []) {
        $this->options = array_merge([
            'useAbsoluteUrls' => !isset($options['useAbsoluteUrls']) || $options['useAbsoluteUrls'] !== false,
            'includeAdMarkers' => isset($options['includeAdMarkers']) ? $options['includeAdMarkers'] : false,
            'addSkipperComment' => !isset($options['addSkipperComment']) || $options['addSkipperComment'] !== false,
            'filterSubtitles' => isset($options['filterSubtitles']) ? $options['filterSubtitles'] : true,
            'subtitleTypes' => ['SUBTITLES', 'CLOSED-CAPTIONS']
        ], $options);
    }

    public function generate($playlist, $options = []) {
        $opts = array_merge($this->options, $options);

        if (!empty($playlist['isMaster'])) {
            return $this->generateMasterPlaylist($playlist, $opts);
        }
        return $this->generateMediaPlaylist($playlist, $opts);
    }

    private function generateMasterPlaylist($playlist, $opts) {
        $output = "#EXTM3U\n";
        $output .= "#EXT-X-VERSION:" . ($playlist['version'] ?? 3) . "\n";

        if (!empty($opts['addSkipperComment'])) {
            $output .= "# Generated by m3u8-ad-skipper\n";
        }

        $filteredMediaTags = [];
        $filteredGroups = [];

        if (!empty($opts['filterSubtitles'])) {
            foreach ($playlist['mediaTags'] ?? [] as $media) {
                $type = $media['type'] ?? '';
                if (!in_array($type, $opts['subtitleTypes'])) {
                    $filteredMediaTags[] = $media;
                } else {
                    $filteredGroups[] = $media['group_id'] ?? '';
                }
            }
        } else {
            $filteredMediaTags = $playlist['mediaTags'] ?? [];
        }

        foreach ($filteredMediaTags as $media) {
            $output .= $media['raw'] . "\n";
        }

        foreach ($playlist['variants'] ?? [] as $variant) {
            $attrs = [];
            if (!empty($variant['bandwidth'])) {
                $attrs[] = "BANDWIDTH=" . $variant['bandwidth'];
            }
            if (!empty($variant['resolution'])) {
                $attrs[] = "RESOLUTION=" . $variant['resolution'];
            }
            if (!empty($variant['codecs'])) {
                $attrs[] = "CODECS=\"" . $variant['codecs'] . "\"";
            }
            if (!empty($variant['name'])) {
                $attrs[] = "NAME=\"" . $variant['name'] . "\"";
            }
            if (!empty($variant['audio']) && !in_array($variant['audio'], $filteredGroups)) {
                $attrs[] = "AUDIO=\"" . $variant['audio'] . "\"";
            }
            if (!empty($variant['video']) && !in_array($variant['video'], $filteredGroups)) {
                $attrs[] = "VIDEO=\"" . $variant['video'] . "\"";
            }
            if (!empty($opts['filterSubtitles'])) {
                if (!empty($variant['subtitles']) && !in_array($variant['subtitles'], $filteredGroups)) {
                    $attrs[] = "SUBTITLES=\"" . $variant['subtitles'] . "\"";
                }
                if (!empty($variant['closed_captions'])) {
                    $cc = $variant['closed_captions'];
                    if ($cc !== 'NONE' && !in_array($cc, $filteredGroups)) {
                        $attrs[] = "CLOSED-CAPTIONS=\"" . $cc . "\"";
                    }
                }
            } else {
                if (!empty($variant['subtitles'])) {
                    $attrs[] = "SUBTITLES=\"" . $variant['subtitles'] . "\"";
                }
                if (!empty($variant['closed_captions'])) {
                    $attrs[] = "CLOSED-CAPTIONS=\"" . $variant['closed_captions'] . "\"";
                }
            }
            $output .= "#EXT-X-STREAM-INF:" . implode(',', $attrs) . "\n";
            $output .= $variant['uri'] . "\n";
        }

        return $output;
    }

    private function generateMediaPlaylist($playlist, $opts) {
        $segments = $playlist['segments'] ?? [];

        if (count($segments) === 0) {
            return $this->generateEmptyPlaylist($playlist, $opts);
        }

        $output = "#EXTM3U\n";
        $output .= "#EXT-X-VERSION:" . ($playlist['version'] ?? 3) . "\n";

        $maxDuration = 0;
        foreach ($segments as $s) {
            if ($s['duration'] > $maxDuration) {
                $maxDuration = $s['duration'];
            }
        }
        $targetDuration = (int)ceil($maxDuration);
        $output .= "#EXT-X-TARGETDURATION:" . $targetDuration . "\n";
        $output .= "#EXT-X-MEDIA-SEQUENCE:" . ($playlist['mediaSequence'] ?? 0) . "\n";

        if (!empty($opts['addSkipperComment'])) {
            $output .= "# Generated by m3u8-ad-skipper\n";
            $originalCount = count($segments) + count($playlist['removedSegments'] ?? []);
            $output .= "# Original segments: " . $originalCount . "\n";
            $output .= "# Removed segments: " . count($playlist['removedSegments'] ?? []) . "\n";
        }

        $prevOriginalIndex = -1;
        for ($i = 0; $i < count($segments); $i++) {
            $segment = $segments[$i];
            $currentOriginalIndex = $segment['originalIndex'] ?? $i;

            if ($i > 0 && $currentOriginalIndex !== $prevOriginalIndex + 1) {
                $output .= "#EXT-X-DISCONTINUITY\n";
            }

            if (!empty($segment['discontinuity']) && $i > 0) {
                $output .= "#EXT-X-DISCONTINUITY\n";
            }

            if (!empty($segment['byteRange'])) {
                $offset = $segment['byteRange']['offset'] ?? 0;
                $output .= "#EXT-X-BYTERANGE:" . $segment['byteRange']['length'] . "@" . $offset . "\n";
            }

            $title = $segment['title'] ?? '';
            $output .= "#EXTINF:" . number_format($segment['duration'], 3, '.', '') . "," . $title . "\n";

            $uri = !empty($opts['useAbsoluteUrls']) && !empty($segment['absoluteUri'])
                ? $segment['absoluteUri']
                : $segment['uri'];
            $output .= $uri . "\n";

            $prevOriginalIndex = $currentOriginalIndex;
        }

        if (!isset($playlist['endlist']) || $playlist['endlist'] !== false) {
            $output .= "#EXT-X-ENDLIST\n";
        }

        return $output;
    }

    private function generateEmptyPlaylist($playlist, $opts) {
        $output = "#EXTM3U\n";
        $output .= "#EXT-X-VERSION:" . ($playlist['version'] ?? 3) . "\n";
        $output .= "#EXT-X-TARGETDURATION:10\n";
        $output .= "#EXT-X-MEDIA-SEQUENCE:0\n";
        if (!empty($opts['addSkipperComment'])) {
            $output .= "# Generated by m3u8-ad-skipper\n";
            $output .= "# Warning: All segments were removed as ads\n";
        }
        $output .= "#EXT-X-ENDLIST\n";
        return $output;
    }

    public function generateJson($playlist, $options = []) {
        $data = [
            'version' => $playlist['version'] ?? null,
            'targetDuration' => $playlist['targetDuration'] ?? null,
            'mediaSequence' => $playlist['mediaSequence'] ?? 0,
            'segmentCount' => count($playlist['segments'] ?? []),
            'removedCount' => count($playlist['removedSegments'] ?? []),
            'segments' => array_map(function($s) {
                return [
                    'uri' => $s['uri'],
                    'duration' => $s['duration'],
                    'title' => $s['title'] ?? ''
                ];
            }, $playlist['segments'] ?? []),
            'removedSegments' => array_map(function($s) {
                return [
                    'uri' => $s['uri'],
                    'duration' => $s['duration'],
                    'matchedRules' => array_map(function($r) {
                        return $r['name'];
                    }, $s['adInfo']['matchedRules'] ?? [])
                ];
            }, $playlist['removedSegments'] ?? [])
        ];
        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
    }

    public function generateStats($playlist, $options = []) {
        $segments = $playlist['segments'] ?? [];
        $removed = $playlist['removedSegments'] ?? [];
        $totalSegments = count($segments) + count($removed);
        
        $totalDuration = 0;
        foreach ($segments as $s) {
            $totalDuration += $s['duration'];
        }
        
        $adDuration = 0;
        foreach ($removed as $s) {
            $adDuration += $s['duration'];
        }

        return [
            'totalSegments' => $totalSegments,
            'keptSegments' => count($segments),
            'removedSegments' => count($removed),
            'totalDuration' => round(($totalDuration + $adDuration) * 100) / 100,
            'contentDuration' => round($totalDuration * 100) / 100,
            'adDuration' => round($adDuration * 100) / 100,
            'adPercentage' => ($totalDuration + $adDuration) > 0
                ? round(($adDuration / ($totalDuration + $adDuration)) * 10000) / 100
                : 0
        ];
    }

    public function toFile($playlist, $filePath, $options = []) {
        $content = $this->generate($playlist, $options);
        file_put_contents($filePath, $content);
        return $filePath;
    }
}
