class OutputGenerator {
  constructor(options = {}) {
    this.options = {
      useAbsoluteUrls: options.useAbsoluteUrls !== false,
      includeAdMarkers: options.includeAdMarkers || false,
      addSkipperComment: options.addSkipperComment !== false,
      ...options
    };
  }

  generate(playlist, options = {}) {
    const opts = { ...this.options, ...options };

    if (playlist.isMaster) {
      return this.generateMasterPlaylist(playlist, opts);
    }
    return this.generateMediaPlaylist(playlist, opts);
  }

  generateMasterPlaylist(playlist, opts) {
    let output = '#EXTM3U\n';
    output += `#EXT-X-VERSION:${playlist.version || 3}\n`;

    if (opts.addSkipperComment) {
      output += '# Generated by m3u8-ad-skipper\n';
    }

    for (const variant of playlist.variants || []) {
      let attrs = [];
      if (variant.bandwidth) {
        attrs.push(`BANDWIDTH=${variant.bandwidth}`);
      }
      if (variant.resolution) {
        attrs.push(`RESOLUTION=${variant.resolution}`);
      }
      if (variant.codecs) {
        attrs.push(`CODECS="${variant.codecs}"`);
      }
      if (variant.name) {
        attrs.push(`NAME="${variant.name}"`);
      }
      output += `#EXT-X-STREAM-INF:${attrs.join(',')}\n`;
      output += `${variant.uri}\n`;
    }

    return output;
  }

  generateMediaPlaylist(playlist, opts) {
    const segments = playlist.segments || [];
    
    if (segments.length === 0) {
      return this.generateEmptyPlaylist(playlist, opts);
    }

    let output = '#EXTM3U\n';
    output += `#EXT-X-VERSION:${playlist.version || 3}\n`;

    const targetDuration = Math.ceil(Math.max(...segments.map(s => s.duration)));
    output += `#EXT-X-TARGETDURATION:${targetDuration}\n`;
    output += `#EXT-X-MEDIA-SEQUENCE:${playlist.mediaSequence || 0}\n`;

    if (opts.addSkipperComment) {
      output += '# Generated by m3u8-ad-skipper\n';
      output += `# Original segments: ${(playlist.segments?.length || 0) + (playlist.removedSegments?.length || 0)}\n`;
      output += `# Removed segments: ${playlist.removedSegments?.length || 0}\n`;
    }

    for (let i = 0; i < segments.length; i++) {
      const segment = segments[i];

      if (segment.discontinuity && i > 0) {
        output += '#EXT-X-DISCONTINUITY\n';
      }

      if (segment.byteRange) {
        const offset = segment.byteRange.offset || 0;
        output += `#EXT-X-BYTERANGE:${segment.byteRange.length}@${offset}\n`;
      }

      const title = segment.title || '';
      output += `#EXTINF:${segment.duration.toFixed(3)},${title}\n`;

      const uri = opts.useAbsoluteUrls && segment.absoluteUri 
        ? segment.absoluteUri 
        : segment.uri;
      output += `${uri}\n`;
    }

    if (playlist.endlist !== false) {
      output += '#EXT-X-ENDLIST\n';
    }

    return output;
  }

  generateEmptyPlaylist(playlist, opts) {
    let output = '#EXTM3U\n';
    output += `#EXT-X-VERSION:${playlist.version || 3}\n`;
    output += '#EXT-X-TARGETDURATION:10\n';
    output += '#EXT-X-MEDIA-SEQUENCE:0\n';
    if (opts.addSkipperComment) {
      output += '# Generated by m3u8-ad-skipper\n';
      output += '# Warning: All segments were removed as ads\n';
    }
    output += '#EXT-X-ENDLIST\n';
    return output;
  }

  generateJson(playlist, options = {}) {
    return JSON.stringify({
      version: playlist.version,
      targetDuration: playlist.targetDuration,
      mediaSequence: playlist.mediaSequence || 0,
      segmentCount: playlist.segments?.length || 0,
      removedCount: playlist.removedSegments?.length || 0,
      segments: playlist.segments?.map(s => ({
        uri: s.uri,
        duration: s.duration,
        title: s.title
      })) || [],
      removedSegments: playlist.removedSegments?.map(s => ({
        uri: s.uri,
        duration: s.duration,
        matchedRules: s.adInfo?.matchedRules?.map(r => r.name) || []
      })) || []
    }, null, 2);
  }

  generateStats(playlist, options = {}) {
    const segments = playlist.segments || [];
    const removed = playlist.removedSegments || [];
    const totalSegments = segments.length + removed.length;
    const totalDuration = segments.reduce((sum, s) => sum + s.duration, 0);
    const adDuration = removed.reduce((sum, s) => sum + s.duration, 0);

    return {
      totalSegments,
      keptSegments: segments.length,
      removedSegments: removed.length,
      totalDuration: Math.round((totalDuration + adDuration) * 100) / 100,
      contentDuration: Math.round(totalDuration * 100) / 100,
      adDuration: Math.round(adDuration * 100) / 100,
      adPercentage: totalDuration + adDuration > 0
        ? Math.round((adDuration / (totalDuration + adDuration)) * 10000) / 100
        : 0
    };
  }

  toFile(playlist, filePath, options = {}) {
    const fs = require('fs');
    const content = this.generate(playlist, options);
    fs.writeFileSync(filePath, content, 'utf8');
    return filePath;
  }
}

module.exports = OutputGenerator;
